name: pythongis
channels:
    - conda-forge
dependencies:
    - python=3.*
    - folium
    - gdal
    - pandas
    - geopandas
    - matplotlib
    - numpy
    - jupyter
    - rasterio
    - requests
    - yaml
    - Cython>=0.16
    - shapely>=1.2.18
    - fiona>=1.0.1
    - pyproj>=1.9.3
    - six>=1.3.0
